export const TEST_CONTACT = {
  name: 'E2E Test Contact',
  company: 'Test Corp',
  role: 'CTO',
}

export const TEST_IDEA = {
  title: 'E2E Test Idea',
  description: 'An idea created by Playwright E2E tests',
}

export const MOCK_IMPORT_RESPONSE = {
  success: true,
  data: {
    importId: 'test-import-id',
    rawText: 'Raw content from the uploaded document for testing purposes.',
    structured: {
      title: 'E2E Import Test Note',
      tags: ['e2e', 'test', 'playwright'],
      content: 'This is the extracted content from the test document. It contains structured information about AI ventures in China and USA markets.',
    },
  },
}

export const MOCK_SYNTHESIS_RESPONSE = {
  success: true,
  data: {
    id: 'test-thesis-id',
    content: `# Investment Thesis

## Overview
This is a test synthesis generated by Playwright E2E tests.

## China Market
Key observations from field notes indicate strong AI infrastructure growth.

## USA Market
Silicon Valley continues to dominate with foundation model startups.

## Key Contacts
Notable introductions made this quarter across both markets.

## Recommended Actions
Focus on cross-border opportunities in AI tooling.`,
    generated_at: new Date().toISOString(),
  },
}
